<#
Deploys the Phase 2 AWS demo stack and publishes the trained backend/ML images.

The stack runs the same Keycloak realm used locally on the EC2 host. Database and HMAC secrets
are generated by CloudFormation and retrieved only by the instance role.
#>
param(
    [string]$StackName = "credisynch-phase2",
    [string]$Region = $(if ($env:AWS_REGION) { $env:AWS_REGION } else { "ap-south-1" }),
    [string]$PublicHost = ":80",
    [switch]$SkipImages
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$template = Join-Path $root "infra\aws\phase2-stack.yml"

Set-Location $root
$callerArn = aws sts get-caller-identity --region $Region --query Arn --output text
if ($callerArn -match ':root$') {
    throw "Refusing to deploy with the AWS account root identity. Authenticate as the aadi-dev deploy user, then rerun this script."
}
Write-Host "Validating CloudFormation template..." -ForegroundColor Cyan
aws cloudformation validate-template --region $Region --template-body "file://$template" | Out-Null

Write-Host "Deploying $StackName in $Region..." -ForegroundColor Cyan
aws cloudformation deploy `
    --region $Region `
    --stack-name $StackName `
    --template-file $template `
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM `
    --no-fail-on-empty-changeset `
    --parameter-overrides `
        "EnvironmentName=$StackName" `
        "PublicHost=$PublicHost"

function Get-Output([string]$key) {
    $value = aws cloudformation describe-stacks `
        --region $Region `
        --stack-name $StackName `
        --query "Stacks[0].Outputs[?OutputKey=='$key'].OutputValue | [0]" `
        --output text
    if ([string]::IsNullOrWhiteSpace($value) -or $value -eq "None") {
        throw "CloudFormation output '$key' was not found."
    }
    return $value.Trim()
}

$backendRepository = Get-Output "BackendRepositoryUri"
$mlRepository = Get-Output "MlRepositoryUri"
$instanceId = Get-Output "InstanceId"
$apiUrl = Get-Output "ApiUrl"
$mlHealthUrl = Get-Output "MlHealthUrl"
$keycloakUrl = Get-Output "KeycloakUrl"

if (-not $SkipImages) {
    Write-Host "Packaging the backend JAR..." -ForegroundColor Cyan
    Push-Location (Join-Path $root "backend")
    mvn -B -DskipTests package
    if ($LASTEXITCODE -ne 0) { Pop-Location; throw "Backend Maven package failed." }
    Pop-Location

    $registry = ($backendRepository -split "/")[0]
    Write-Host "Logging into ECR..." -ForegroundColor Cyan
    aws ecr get-login-password --region $Region | docker login --username AWS --password-stdin $registry

    Write-Host "Building and pushing backend image..." -ForegroundColor Cyan
    docker build -t "$backendRepository`:latest" -f backend\Dockerfile .
    docker push "$backendRepository`:latest"

    Write-Host "Building and pushing trained ML image..." -ForegroundColor Cyan
    if (-not (Test-Path (Join-Path $root "ml-service\models\model.txt"))) {
        throw "Trained model artifact is missing. Run scripts\train-model.ps1 before deploying."
    }
    docker build -t "$mlRepository`:latest" -f ml-service\Dockerfile .\ml-service
    docker push "$mlRepository`:latest"
}

Write-Host "Refreshing the EC2 services through SSM..." -ForegroundColor Cyan
$realmPath = Join-Path $root "infra\keycloak\realm-credisynch.json"
if (-not (Test-Path $realmPath)) {
    throw "Keycloak realm file is missing: $realmPath"
}
$realmText = Get-Content -Raw $realmPath
# The IP demo is intentionally HTTP. Local development keeps the stricter external setting.
$realmText = $realmText.Replace('"sslRequired": "external"', '"sslRequired": "none"')
$realmBase64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($realmText))
$remoteCommands = @(
    "echo '$realmBase64' | base64 -d | sudo tee /opt/credisynch/realm-credisynch.json >/dev/null",
    "sudo /opt/credisynch/deploy.sh"
)
$ssmParameters = @{ commands = $remoteCommands } | ConvertTo-Json -Compress
$ssmParametersPath = Join-Path $env:TEMP "credisynch-ssm-$([Guid]::NewGuid()).json"
try {
    # Passing JSON through a native PowerShell argument strips its quotes. A file:// parameter
    # preserves the JSON exactly for the AWS CLI.
    Set-Content -LiteralPath $ssmParametersPath -Value $ssmParameters -Encoding ascii
    $commandId = aws ssm send-command `
        --region $Region `
        --instance-ids $instanceId `
        --document-name AWS-RunShellScript `
        --comment "CrediSynch Phase 2 deploy" `
        --parameters "file://$ssmParametersPath" `
        --query "Command.CommandId" `
        --output text
} finally {
    Remove-Item -LiteralPath $ssmParametersPath -Force -ErrorAction SilentlyContinue
}
if ([string]::IsNullOrWhiteSpace($commandId)) { throw "SSM deployment command was not created." }

for ($i = 0; $i -lt 60; $i++) {
    Start-Sleep -Seconds 5
    $invocation = aws ssm get-command-invocation --region $Region --command-id $commandId --instance-id $instanceId | ConvertFrom-Json
    if ($invocation.Status -in @("Success", "Failed", "Cancelled", "TimedOut")) {
        if ($invocation.StandardOutputContent) { Write-Host $invocation.StandardOutputContent }
        if ($invocation.Status -ne "Success") {
            if ($invocation.StandardErrorContent) { Write-Error $invocation.StandardErrorContent }
            throw "Remote deploy finished with status $($invocation.Status)."
        }
        break
    }
    if ($i -eq 59) { throw "Timed out waiting for SSM command $commandId." }
}

Write-Host "" 
Write-Host "Phase 2 AWS deployment complete." -ForegroundColor Green
Write-Host "API            : $apiUrl"
Write-Host "ML health      : $mlHealthUrl"
Write-Host "Keycloak       : $keycloakUrl"
